function [total_time, total_dist, total_fuel] = race_sim( ...
  out_start_to_t2, flying_start_to_t2, ...
  t2_to_t10, in_t10_to_finish, flying_t10_to_finish)
  
  total_time = ...
               3 * out_start_to_t2.seg_time + ...
               6 * flying_start_to_t2.seg_time + ...
               9 * t2_to_t10.seg_time + ...
               3 * in_t10_to_finish.seg_time + ...
               6 * flying_t10_to_finish.seg_time;

  total_fuel = ...
               3 * out_start_to_t2.seg_fuel + ...
               6 * flying_start_to_t2.seg_fuel + ...
               9 * t2_to_t10.seg_fuel + ...
               3 * in_t10_to_finish.seg_fuel + ...
               6 * flying_t10_to_finish.seg_fuel;

  total_dist = ...
               3 * out_start_to_t2.seg_dist + ...
               6 * flying_start_to_t2.seg_dist + ...
               9 * t2_to_t10.seg_dist + ...
               3 * in_t10_to_finish.seg_dist + ...
               6 * flying_t10_to_finish.seg_dist;

end