time_standing_start_to_t2

time_out_start_to_t2
time_flying_start_to_t2

time_t2_to_t10

time_in_t10_to_finish
time_flying_t10_to_finish

time_total = time_standing_start_to_t2 + ...
             2 * time_out_start_to_t2 + ...
             6 * time_flying_start_to_t2 + ...
             9 * time_t2_to_t10 + ...
             3 * time_in_t10_to_finish + ...
             6 * time_flying_t10_to_finish;
